#!/usr/bin/env python
import re

FILE='../../../ring-puppet/manifests/ring-users.pp'

file = open(FILE,"r");

p = {};
k = [];
for line in file:
    line=line.rstrip()
    if re.search(r'# BEGIN ',line):
        p.clear()
        k = [];

    if re.search(r'add_user',line):
        username = line
        username = re.sub('\s*@add_user\s+{\s+\'','',username)
        username = re.sub('\':.*','',username)
        p['username'] = username
    
    if re.search(r'^\s*email',line):
        nocmail = line
        nocmail = re.sub('\s*email\s+=>\s+\'','',nocmail)
        nocmail = re.sub('\',.*','',nocmail)
        p['nocmail'] = nocmail
    
    if re.search(r'^\s*company',line):
        company = line
        company = re.sub('\s*company\s+=>\s+\'','',company)
        company = re.sub('\',.*','',company)
        p['company'] = company
    
    if re.search(r'^\s*uid',line):
        userid = line
        userid = re.sub('\s*uid\s+=>\s+','',userid)
        userid = re.sub(',.*','',userid)
        p['userid'] = userid
    
    if re.search(r'ensure\s+=>\s+absent',line):
        p['absent'] = 1
    
    if re.search(r'\'ssh-',line):
        sshkey = line
        sshkey = re.sub('\s+\'','',sshkey)
        sshkey = re.sub('\',.*','',sshkey)
        words = sshkey.split()
        sshkey = words[0]+" "+words[1]
        if len(words) > 2:
            sshkey = sshkey+" "+words[2]
        k.append(sshkey)

    if re.search(r'# END ',line):
        if p.has_key('absent'):
            continue
        print "../ring-admin add participant"+\
              " \""+p['company']+"\""\
              " \"\""+\
              " \"\""+\
              " "+p['nocmail']+\
              " "+p['username']
        print "../ring-admin update user "+\
              p['username']+" userid "+p['userid']
        for key in k:
            print "echo \""+key+"\" | ../ring-admin add sshkeys "+p['username']
