#!/usr/bin/env bash
# Written by Martin Pels <martin@rodecker.nl>
# Improved by Miek Gieben <miek@miek.nl>
set -e

keyfile="${HOME}/.ssh/ring.nlnog.net"

if [ $# -eq 0 ]; then
    echo $0: need ssh command line >&2
    exit 1
fi
if [ ! -f $keyfile ]; then
    echo $0: key file $keyfile not found >&2
    exit 1
fi

export SSH_AUTH_SOCK=${TMPDIR:-/tmp}"/ssh-ring-$LOGNAME/agent.ring"
if [ ! -d $(dirname $SSH_AUTH_SOCK) ]; then
    mkdir $(dirname $SSH_AUTH_SOCK)
fi
if [ ! -S $SSH_AUTH_SOCK ];
then 
    eval $(ssh-agent -a $SSH_AUTH_SOCK)
    ssh-add -D
    ssh-add $keyfile
fi
host=$1
if [[ $host != *"ring.nlnog.net" ]]; then
  host=$host.ring.nlnog.net
fi
ssh -A $host ${@:2}
