#!/usr/bin/env bash

if [ $# -ne 1 ]
then
    echo -e "No arguments were given\n
    Usuage: `basename $0` all 
    This script will rsync the contents of ~/.ssh/ from this server to all ring servers
    Keep the following things in mind:
        - puppet will ensure that the ssh key you gave to the ring-admins is always present on all servers
        - you are responsible for the additional keys that are synced to all servers through this script
        - only add keys of your co-workers
        - this script will overwrite the .ssh/authorized_keys file on all other servers
"
    exit 1
fi

if [ $1 = "all" ]
then 
    SERVERS=$(dig -t txt +short ring.nlnog.net)
    SERVERS=${SERVERS//'"'/}

    for host in $SERVERS
    do
        echo $host.ring.nlnog.net
        rsync -avHP ~/.ssh/* $host.ring.nlnog.net:.ssh/
    done
    exit 0
fi
