#!/usr/bin/env bash
# Written by Sten Spans <sten@snore.nl> 

ping="ping"

while getopts "6vh" flag; do
    case $flag in
	6)
	    ping="ping6"
	    ;;
	v)
	    verbose=1
	    ;;
	*)
	    echo "Usage: $(basename $0) [-6v] host"
	    exit 1
	    ;;
    esac
done

shift $((OPTIND-1))

if [ $# -lt 1 ]; then
    echo "Usage: $(basename $0) [-6v] host"
    exit 1
fi

host=$1
[ -n "${host//[^:]}" ] && ping="ping6"


ping_cmd="echo '\$(hostname -s)': '\$(${ping} -c1 -W1 $host | grep ^rtt)'"
ssh_cmd="ssh -q -o ConnectTimeout=2 {}.ring.nlnog.net ${ping_cmd}" 

SERVERS=$(dig -t txt +short ring.nlnog.net | tr -d '"' | tr ' ' '\n')

declare -a results
declare -a replies
declare -a timeouts

while read line; do
    server=${line%%:*}
    output=${line#*:}

    results=( ${results[@]} ${server} )

    if [ -n "${output}" ]; then
	time=`echo $output | cut -f6 -d/`
	replies=( ${replies[@]} ${time} )
	[ -n "${verbose}" ] && printf "%-30s %s\n" ${server}: $time
    else
	timeouts=( ${timeouts[@]} $server )
	[ -n "${verbose}" ] && printf "%-20s %s\n" ${server}: timeout
    fi

done < <(echo "$SERVERS" | xargs -P10 -n1 -I{} sh -c "${ssh_cmd}||:")

if [ -n "${replies[*]}" ]; then
    total=0
    for t in ${replies[@]}; do
	total=$(echo $total + $t | bc)
    done
    avg=$(echo $total / ${#replies[@]} | bc)
    echo ${#replies[@]} servers: ${avg}ms average
fi

[ -z "${timeouts[*]}" ] || echo unreachable via: ${timeouts[@]}

connect=$(comm -23 <(echo "${SERVERS}" | sort) \
    <(echo ${results[@]} | tr ' ' '\n' | sort))
[ -z "${connect[*]}" ] || echo ssh connection failed: ${connect[@]}

