#!/usr/bin/env bash

ping="ping"
if [ "$1" = "-6" ]; then
    ping="ping6"
    shift
elif [ -n "${1//[^:]}" ]; then
    ping="ping6"
fi

if [ $# -lt 1 ]; then
    echo "Usuage: $(basename $0) [-6] host"
    exit 1
fi

host=$1

ping_cmd="echo \`hostname -s\`: \`${ping} -c1 -W1 $host | grep ^rtt\`"
ssh_cmd="ssh -q -t -o ConnectTimeout=2 {}.ring.nlnog.net ${ping_cmd}" 

SERVERS=$(dig -t txt +short ring.nlnog.net | tr -d '"' | tr ' ' '\n')

declare -a replies
declare -a timeouts

while read line; do
    server=${line%%:*}
    output=${line#*:}

    if [ -n "${output}" ]; then
	time=`echo $output | cut -f6 -d/`
	replies=( ${replies[@]} ${time} )
    else
	timeouts=( ${timeouts[@]} $server )
    fi
done < <(echo "$SERVERS" | xargs -P10 -n1 -I{} ${ssh_cmd} 2>/dev/null)

if [ -n "${replies[*]}" ]; then
    total=0
    for t in ${replies[@]}; do
	total=$(echo $total + $t | bc)
    done
    avg=$(echo $total / ${#replies[@]} | bc)
    echo ${#replies[@]} servers: ${avg}ms average
fi

[ -z "${timeouts[*]}" ] || echo unreachable via: ${timeouts[@]}

