#!/usr/bin/env bash
# Written by Martin Pels <martin@rodecker.nl>
# Improved by Miek Gieben <miek@miek.nl>

export SSH_AUTH_SOCK=${TMPDIR:-/tmp}"/ssh-ring-$LOGNAME/agent.ring"
if [ ! -d $(dirname $SSH_AUTH_SOCK) ]; then
    mkdir $(dirname $SSH_AUTH_SOCK)
fi
if [ ! -S $SSH_AUTH_SOCK ];
then 
    eval $(ssh-agent -a $SSH_AUTH_SOCK)
    ssh-add ~/.ssh/ring.nlnog.net
fi
ssh -A $@
